services:
  - type: web
    name: nutrify-backend
    env: docker
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: gunicorn bharathi_project.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DB_NAME
        value: railway
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: CIDnUfhvXPaDAmXRlYVgPHLpgsHRSEpc
      - key: DB_HOST
        value: yamabiko.proxy.rlwy.net
      - key: DB_PORT
        value: "34361"
