services:
  - type: web
    name: nutrify-backend
    env: docker
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: gunicorn bharathi_project.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DB_NAME
        value: nutrify_db_dlel
      - key: DB_USER
        value: bharathi
      - key: DB_PASSWORD
        value: va4D3soijcC6qzYdGrybEoVmtnhyX1Dy
      - key: DB_HOST
        value: dpg-d11f5uvdiees73faaj0g-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DEBUG
        value: "True"
      - key: SECRET_KEY
        value: your_super_secret_key
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CLOUDINARY_CLOUD_NAME
        value: dozq91mif
      - key: CLOUDINARY_API_KEY
        value: "525988449794638"
      - key: CLOUDINARY_API_SECRET
        value: PRhFPBUBA-pzvqqZrYLB73gFF54
      - key: RAZORPAY_KEY_ID
        value: rzp_test_AciNtl2tzsXSNM
      - key: RAZORPAY_KEY_SECRET
        value: PhVmK1Q5aOW54imScMYvwB1T   
